# -*- coding: utf-8 -*-
"""PCD-sesi9

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IDY1ks32Gwgxg8wyIx33nCRZiXd7ah9v
"""

pip install numpy imageio matplotlib scipy

import numpy as np
import imageio.v3 as imageio
import matplotlib.pyplot as plt
from scipy.signal import convolve2d

def roberts_edge_detection(image):
    roberts_cross_v = np.array([[1, 0], [0, -1]])
    roberts_cross_h = np.array([[0, 1], [-1, 0]])

    vertical = np.abs(convolve2d(image, roberts_cross_v, mode='same'))
    horizontal = np.abs(convolve2d(image, roberts_cross_h, mode='same'))

    roberts_edge = np.sqrt(vertical**2 + horizontal**2)

    return roberts_edge

def sobel_edge_detection(image):
    sobel_x = np.array([[-1, 0, 1], [-2, 0, 2], [-1, 0, 1]])
    sobel_y = np.array([[-1, -2, -1], [0, 0, 0], [1, 2, 1]])

    gradient_x = np.abs(convolve2d(image, sobel_x, mode='same'))
    gradient_y = np.abs(convolve2d(image, sobel_y, mode='same'))

    sobel_edge = np.sqrt(gradient_x**2 + gradient_y**2)

    return sobel_edge

def load_and_preprocess_image(image_path):
    image = imageio.imread(image_path)

    if len(image.shape) == 3:
        image = np.mean(image, axis=2)

    image = (image - np.min(image)) / (np.max(image) - np.min(image))

    return image

def compare_edge_detection(image_path):
    image = load_and_preprocess_image(image_path)

    roberts_edges = roberts_edge_detection(image)
    sobel_edges = sobel_edge_detection(image)

    plt.figure(figsize=(15, 5))

    plt.subplot(1, 3, 1)
    plt.title('Citra Asli')
    plt.imshow(image, cmap='gray')
    plt.axis('off')

    plt.subplot(1, 3, 2)
    plt.title('Roberts Edge Detection')
    plt.imshow(roberts_edges, cmap='gray')
    plt.axis('off')

    plt.subplot(1, 3, 3)
    plt.title('Sobel Edge Detection')
    plt.imshow(sobel_edges, cmap='gray')
    plt.axis('off')

    plt.tight_layout()
    plt.show()

    print("Analisis Deteksi Tepi:")
    print(f"Roberts - Rata-rata intensitas tepi: {np.mean(roberts_edges):.4f}")
    print(f"Roberts - Standar deviasi tepi: {np.std(roberts_edges):.4f}")
    print(f"Sobel - Rata-rata intensitas tepi: {np.mean(sobel_edges):.4f}")
    print(f"Sobel - Standar deviasi tepi: {np.std(sobel_edges):.4f}")

# Contoh penggunaan
compare_edge_detection(r'/content/Rmh.jpg')